import {creatorConfigKey} from '../lib/creator-execution';
import {test} from 'node:test';
import {saveCreatorExits,adoptCreatorExits} from '../lib/creator-exits';
import {perpCoverage} from '../lib/perps';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {validateExitPlan,startExitState,evaluateExitState,type ExitPlan} from '../lib/exit-plan';
import {paperTrade} from '../lib/paper-trading';
import {EXAMPLES,type Thesis} from '../lib/data';
import {paperPerformance,type PaperOrder} from '../lib/performance';
import {suggestExitStrategy} from '../lib/ai/exit-strategy';
const plan:ExitPlan={id:'creator-plan',mode:'tokens',steps:[{symbol:'BTC',targetPct:10,sellPct:25},{symbol:'BTC',targetPct:20,sellPct:25},{symbol:'BTC',targetPct:30,sellPct:50},{symbol:'ETH',targetPct:50,sellPct:100}],rationale:'Scale out as adoption develops.',origin:'creator',updatedAt:1};
const thesis:Thesis={...EXAMPLES.find(t=>t.id==='majors-bottom')!,id:'exit-test',owner:'creator',example:false,allocations:[{symbol:'BTC',weight:60},{symbol:'ETH',weight:40}],exitPlan:plan};
function fixture(){const sqlite=new DatabaseSync(':memory:');for(const name of readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL(`../drizzle/${name}`,import.meta.url),'utf8'));for(const user of ['creator','investor'])sqlite.prepare('INSERT INTO accounts(user_id) VALUES(?)').run(user);sqlite.prepare('INSERT INTO theses(id,owner,payload,created_at) VALUES(?,?,?,?)').run(thesis.id,'creator',JSON.stringify(thesis),1);
 let fail=false;
 class Statement{values:(string|number|null)[]=[];constructor(public sql:string){}bind(...v:(string|number|null)[]){this.values=v;return this;}async first(){return sqlite.prepare(this.sql).get(...this.values)||null;}async all(){return {results:sqlite.prepare(this.sql).all(...this.values),success:true};}async run(){const r=sqlite.prepare(this.sql).run(...this.values);return {meta:{changes:Number(r.changes)},success:true};}}
 const db={prepare:(sql:string)=>new Statement(sql),async batch(rows:Statement[]){sqlite.exec('BEGIN');try{const results=rows.map((r,i)=>{if(fail&&rows.length>2&&i===2)throw new Error('Injected failure');if(r.sql.startsWith('SELECT'))return {results:sqlite.prepare(r.sql).all(...r.values),success:true};const x=sqlite.prepare(r.sql).run(...r.values);return {results:[],meta:{changes:Number(x.changes)},success:true};});sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}} as unknown as D1Database;
 const trade=(action:'buy'|'sell'|'simulate',amount:number,options:Record<string,unknown>={})=>paperTrade(db,'investor',thesis,{id:crypto.randomUUID(),action,amount,configKey:creatorConfigKey(thesis),exitPlanId:thesis.exitPlan?.id??null,acceptProfitShare:true,...options});
 const position=()=>sqlite.prepare('SELECT * FROM positions WHERE user_id=?').get('investor') as any;
 return {sqlite,db,trade,position,fail:()=>{fail=true;}};
}
test('validation rejects foreign tokens, missing tokens, descending targets and overselling',()=>{assert.deepEqual(validateExitPlan(plan,thesis),plan);assert.throws(()=>validateExitPlan({...plan,steps:plan.steps.slice(0,3)},thesis),/100%/);assert.throws(()=>validateExitPlan({...plan,steps:[...plan.steps,{symbol:'SOL',targetPct:100,sellPct:100}]},thesis),/basket/);assert.throws(()=>validateExitPlan({...plan,steps:plan.steps.map((s,i)=>i===1?{...s,targetPct:5}:s)},thesis),/increase/);assert.throws(()=>validateExitPlan({...plan,steps:plan.steps.map((s,i)=>i===0?{...s,sellPct:50}:s)},thesis),/100%/);});
test('25/25/50 sells original quantities, completed stages never repeat, only targeted token sells',()=>{let state=startExitState(plan,thesis,100000,100000);const a=evaluateExitState(state,thesis,11);assert.equal(a.proceeds,16650);assert.equal(a.cost,85000);assert.deepEqual(a.state.done,[0]);assert.equal(a.state.legs[1].cost,40000);const down=evaluateExitState(a.state,thesis,-5);assert.equal(down.proceeds,0);const recover=evaluateExitState(down.state,thesis,5);assert.equal(recover.proceeds,0);const b=evaluateExitState(a.state,thesis,10);assert.equal(b.releasedCost,15000);assert.deepEqual(b.state.done,[0,1]);const c=evaluateExitState(b.state,thesis,10);assert.equal(c.state.legs[0].amount,0);assert.equal(c.state.legs[1].cost,40000);});
test('short profit targets execute after declines, while long targets do not',()=>{const t={...thesis,allocations:[{symbol:'BTC',weight:100,side:'short' as const}]};const p={...plan,steps:[{symbol:'BTC',targetPct:20,sellPct:100}]};assert.equal(evaluateExitState(startExitState(p,t,10000,10000),t,-25).proceeds,12500);assert.equal(evaluateExitState(startExitState(p,t,10000,10000),t,25).proceeds,0);});
test('partial creator sales credit net proceeds, retain exact token cost and reconcile portfolio/P&L',async()=>{const f=fixture();await f.trade('buy',100000,{exitPlanId:plan.id});const res=await f.trade('simulate',1,{change:11});assert.equal(res.triggered,true);assert.equal(res.executionReason,'creator-exit');const p=f.position();assert.equal(p.invested,85000);assert.equal(JSON.parse(p.exit_state).legs[1].cost,40000);const orders=f.sqlite.prepare('SELECT id,thesis_id AS thesisId,side,amount,creator_fee AS creatorFee,trading_fee AS tradingFee,platform_profit_fee AS platformProfitFee,cost_basis AS costBasis,created_at AS createdAt FROM orders WHERE user_id=? ORDER BY created_at,rowid').all('investor') as PaperOrder[];assert.deepEqual(orders.map(o=>o.side),['buy','scenario','sell']);assert.equal(orders[2].costBasis,15000);const cash=f.sqlite.prepare('SELECT balance FROM accounts WHERE user_id=?').get('investor')!.balance as number;const perf=paperPerformance(orders,[{id:p.id,thesisId:thesis.id,amount:p.amount,invested:p.invested,takeProfit:null,stopLoss:null}],cash,Date.now());assert.equal(perf.tradePnl[orders[2].id].cost,150);assert.notEqual(perf.tradePnl[orders[2].id].profit,null);assert.equal(Math.round(perf.equity*100),cash+p.amount);assert.equal(f.sqlite.prepare('SELECT SUM(amount) AS amount FROM creator_earnings').get()!.amount,res.creatorFee);});
test('plan snapshots survive creator changes; stale confirmations and top ups cannot reset completed stages',async()=>{const f=fixture();await assert.rejects(()=>f.trade('buy',10000,{exitPlanId:'outdated'}),/current/);await f.trade('buy',100000,{exitPlanId:plan.id});thesis.exitPlan={...plan,id:'updated',steps:plan.steps.map(s=>({...s,targetPct:s.targetPct+200}))};try{await f.trade('simulate',1,{change:11});assert.equal(JSON.parse(f.position().exit_state).plan.id,plan.id);assert.deepEqual(JSON.parse(f.position().exit_state).done,[0]);await assert.rejects(()=>f.trade('buy',10000),/adding capital/);}finally{thesis.exitPlan=plan;}});
test('duplicate requests cannot execute a second stage, and transaction failures roll back cash and stage progress',async()=>{const f=fixture();await f.trade('buy',100000,{exitPlanId:plan.id});const id=crypto.randomUUID();const input={id,action:'simulate' as const,amount:1,change:11};await paperTrade(f.db,'investor',thesis,input);const before=JSON.stringify(f.position());const again=await paperTrade(f.db,'investor',thesis,input);assert.equal(again.duplicate,true);assert.equal(JSON.stringify(f.position()),before);f.fail();await assert.rejects(()=>f.trade('simulate',1,{change:20}),/Injected/);assert.equal(JSON.stringify(f.position()),before);});
test('new creator-controlled positions ignore personal overrides and reopen with a fresh creator schedule',async()=>{const f=fixture();await f.trade('buy',100000);f.sqlite.prepare('UPDATE positions SET stop_loss=5 WHERE user_id=?').run('investor');await f.trade('simulate',1,{change:-10});assert.ok(f.position().amount>0);assert.equal(f.position().stop_loss,null);await f.trade('sell',f.position().amount);await f.trade('buy',10000);assert.deepEqual(JSON.parse(f.position().exit_state).done,[]);});
test('AI sends thesis and direction, validates staged totals and rejects incomplete responses without a paid retry',async()=>{let calls=0;const fetcher=async (_:any,init:any)=>{calls++;const request=JSON.parse(init.body);assert.equal(request.store,false);assert.match(request.input,/Scale|BTC|exit-test/);assert.match(request.instructions,/untrusted/);return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({steps:plan.steps,rationale:'A reviewed illustrative schedule.'})}]}]});};const result=await suggestExitStrategy(thesis,'tokens','test-key','suggestion-id',fetcher as typeof fetch);assert.equal(result.origin,'ai');assert.equal(calls,1);await assert.rejects(()=>suggestExitStrategy(thesis,'tokens','test-key','id',(async()=>Response.json({status:'incomplete'})) as typeof fetch),/incomplete/);});

test('only creator can publish targets, compare-and-swap rejects stale edits and existing investor targets remain frozen',async()=>{const f=fixture();await f.trade('buy',100000,{exitPlanId:plan.id});await assert.rejects(()=>saveCreatorExits(f.db,'investor',thesis,plan,plan.id),/Only the creator/);await saveCreatorExits(f.db,'creator',thesis,{...plan,rationale:'Updated by the creator.'},plan.id);await assert.rejects(()=>saveCreatorExits(f.db,'creator',thesis,plan,plan.id),/changed/);const saved=JSON.parse(f.sqlite.prepare('SELECT payload FROM theses WHERE id=?').get(thesis.id)!.payload as string);assert.notEqual(saved.exitPlan.id,plan.id);assert.equal(JSON.parse(f.position().exit_state).plan.id,plan.id);await assert.rejects(()=>saveCreatorExits(f.db,'creator',{...thesis,closedAt:1},plan,saved.exitPlan.id),/closed/);});
test('legacy investor can explicitly adopt targets without resetting a used schedule',async()=>{const f=fixture();await f.trade('buy',100000);f.sqlite.prepare('UPDATE positions SET execution_state=NULL,exit_state=NULL,take_profit=15,stop_loss=10 WHERE user_id=?').run('investor');await adoptCreatorExits(f.db,'investor',thesis,plan.id);assert.equal(f.position().take_profit,null);assert.equal(f.position().stop_loss,10);await f.trade('simulate',1,{change:11});await assert.rejects(()=>adoptCreatorExits(f.db,'investor',thesis,plan.id),/already active/);assert.deepEqual(JSON.parse(f.position().exit_state).done,[0]);});
test('a creator update racing the investment confirmation cannot spend funds with stale targets',async()=>{const f=fixture();f.sqlite.prepare("UPDATE theses SET payload=json_set(payload,'$.exitPlan.id','new-plan') WHERE id=?").run(thesis.id);await assert.rejects(()=>f.trade('buy',10000,{exitPlanId:plan.id}),/Refresh/);assert.equal(f.position(),undefined);assert.equal(f.sqlite.prepare('SELECT balance FROM accounts WHERE user_id=?').get('investor')!.balance,1000000);});
test('basket-stage perps reduce collateral and notional together; liquidation retains priority',async()=>{const f=fixture(),basket={...plan,mode:'basket' as const,steps:[{symbol:null,targetPct:20,sellPct:50},{symbol:null,targetPct:50,sellPct:50}]},take={...thesis,exitPlan:basket,allocations:thesis.allocations.map(a=>({...a,execution:'perps' as const,leverage:5}))};f.sqlite.prepare('UPDATE theses SET payload=? WHERE id=?').run(JSON.stringify(take),take.id);const provider=async()=>perpCoverage(take,['BTC','ETH'].map(symbol=>({symbol,maxLeverage:10,maintenanceBps:500,markPrice:100,funding:0})));await paperTrade(f.db,'investor',take,{id:crypto.randomUUID(),action:'buy',amount:100000,configKey:creatorConfigKey(take),executionMode:'perps',leverage:5,acceptRisk:true,acceptProfitShare:true,exitPlanId:basket.id},provider);const initial=f.position().perp_notional;const result=await paperTrade(f.db,'investor',take,{id:crypto.randomUUID(),action:'simulate',amount:1,change:5},provider);assert.equal(result.executionReason,'creator-exit');assert.equal(f.position().invested,50000);assert.ok(f.position().perp_notional<initial);await paperTrade(f.db,'investor',take,{id:crypto.randomUUID(),action:'simulate',amount:1,change:-90},provider);assert.equal(f.position().amount,0);});
