import {wantsStablecoins} from './allocations';
import type {Creator} from './creators';
import type {AIResearch,Exposure} from './ai/types';
import {HORMUZ_MARKET} from './hormuz-market';
import {VITALIK_TOKENS,VITALIK_CALL_ID,VITALIK_PORTFOLIO_PROMPT} from './vitalik-portfolio';
export type Token = {symbol:string; name:string; color:string; icon:string; image?:string; fit:string; reason:string; risk:string; source:string; kind?:Exposure; coingeckoId?:string; identitySource?:string; chain?:string; contract?:string;instrument?:'stock'|'prediction'};
export type Allocation={symbol:string;weight:number;execution?:'spot'|'perps';leverage?:number;side?:'long'|'short'};
export type Thesis={performanceFeeBps?:number;storageVersion?:number;executionVersion?:1;exitPlan?:import("./exit-plan").ExitPlan;closedAt?:number;archivedAt?:number;counter?:import('./counter-strategy').CounterStrategy;id:string;title:string;body:string;summary:string;category:string;author:string;creator?:Creator;owner?:string;allocations:Allocation[];createdAt:number;version:number;parent?:string;example?:boolean;engine:'curated'|'ai';risk:string;evidenceNote?:string;tokens?:Record<string,Token>;research?:AIResearch;generationId?:string;visibility?:'private'|'public';artworkId?:string;artworkStatus?:string};
export type Position={feeTerms?:string|null;executionState?:string|null;exitState?:string|null;id:string;thesisId:string;amount:number;invested:number;takeProfit:number|null;stopLoss:number|null;shareEligible?:boolean;shareRealized?:number;shareHighWater?:number;sharePaid?:number;platformRealized?:number;platformHighWater?:number;platformPaid?:number;executionMode?:'spot'|'perps';leverage?:number;perpNotional?:number;perpWeight?:number;maintenanceBps?:number;perpMarkets?:string|null};
export const TOKENS:Record<string,Token>={
...VITALIK_TOKENS,
BEAM:{symbol:'BEAM',name:'Beam',color:'#dedfe4',image:'/coins/BEAM.png',icon:'beam-2',coingeckoId:'beam-2',fit:'Gaming network',reason:'BEAM powers transactions, network validation and in-game payments across the Beam gaming ecosystem. This is the gaming-network BEAM, distinct from the privacy coin with the same ticker.',risk:'Ecosystem adoption, supply changes and speculative demand can cause sharp moves. Short exposure can lose when new games or network activity attract buyers.',source:'https://token.onbeam.com/',identitySource:'https://api.coingecko.com/api/v3/coins/beam-2',chain:'Ethereum',contract:'0x62d0a8458ed7719fdaf978fe5929c6d342b0bfce'},
ILV:{symbol:'ILV',name:'Illuvium',color:'#7656bd',image:'/coins/ILV.png',icon:'illuvium',coingeckoId:'illuvium',fit:'Game ecosystem & governance',reason:'ILV is the governance token for Illuvium’s interconnected game ecosystem. It represents exposure to a specific game franchise, alongside this basket’s broader gaming networks and virtual worlds.',risk:'Game releases, player demand, staking changes and token supply can drive sudden repricing. A successful game launch or short squeeze can invalidate the bear thesis.',source:'https://docs.illuvium.io/illuvium-whitepaper/tokenomics',identitySource:'https://api.coingecko.com/api/v3/coins/illuvium',chain:'Ethereum',contract:'0x767fe9edc9e0df98e07454847909b5e959d7ca0e'},
USOON:{symbol:'USOon',name:'United States Oil Fund',color:'#bd7547',icon:'united-states-oil-fund-ondo-tokenized',instrument:'stock',fit:'WTI oil-linked ETF token',reason:'Ondo’s USOon references the United States Oil Fund, which uses WTI futures, swaps and related instruments. The token itself is long exposure; a SHORT allocation here is a separate paper simulation intended to benefit from a fall in the underlying fund.',risk:'Fund performance differs from spot oil because of futures roll and tracking. Token liquidity, borrowing costs and squeezes matter. Live borrow or short execution is not connected; Ondo eligibility restrictions apply.',source:'https://app.ondo.finance/assets/usoon',coingeckoId:'united-states-oil-fund-ondo-tokenized',identitySource:'https://raw.githubusercontent.com/ondoprotocol/ondo-global-markets-token-list/main/tokenlist.json',chain:'Ethereum',contract:'0x1F5FC5C3c8B0f15c7e21AF623936ff2B210B6415'},
BNOON:{symbol:'BNOon',name:'United States Brent Oil Fund',color:'#788296',icon:'us-brent-oil-fund-ondo-tokenized',instrument:'stock',fit:'Brent oil-linked ETF token',reason:'Ondo’s BNOon references the United States Brent Oil Fund, which uses Brent-linked futures and related instruments. Its SHORT allocation models the bearish oil thesis in paper funds; buying BNOon itself would be long oil-fund exposure.',risk:'Futures roll, fund tracking, token liquidity and potential short squeezes can change returns. This paper short omits borrowing costs and does not execute at an external venue. Regional eligibility restrictions apply.',source:'https://app.ondo.finance/assets/bnoon',coingeckoId:'us-brent-oil-fund-ondo-tokenized',identitySource:'https://raw.githubusercontent.com/ondoprotocol/ondo-global-markets-token-list/main/tokenlist.json',chain:'Ethereum',contract:'0x9ddb2524782684942FAD28b44E76552cB7f3F548'},
HORMUZYES:{symbol:'YES',name:'Hormuz traffic · Polymarket',color:'#315df8',image:'/coins/polymarket.png',icon:'',instrument:'prediction',fit:'Traffic normalization by November 30',reason:`A YES outcome share for “${HORMUZ_MARKET.question}” ${HORMUZ_MARKET.rules} Winning shares pay $1; losing shares pay $0. This is an external event contract, not a platform token.`,risk:'YES may expire worthless. Reopening headlines can differ from the contract’s traffic threshold. Entry price, liquidity, fees, resolution disputes and regional access matter. This app records an illustrative paper allocation and does not place or automatically settle Polymarket orders.',source:HORMUZ_MARKET.url,identitySource:`https://clob.polymarket.com/markets/${HORMUZ_MARKET.conditionId}`,chain:'Polygon'},
ROBO:{symbol:'ROBO',name:'Fabric Protocol',color:'#6963df',icon:'robo-token-2',fit:'Robot coordination & payments',reason:'Fabric connects robots through identity, payments and verification. ROBO is the protocol token for network fees, staking and governance; it is direct exposure to robot coordination infrastructure.',risk:'ROBO does not represent ownership of robots or a right to revenue. Adoption, liquidity and substantial team and investor vesting can affect token returns. Paper baskets only here.',source:'https://fabric.foundation/blog/introducing-robo',coingeckoId:'robo-token-2',identitySource:'https://www.coingecko.com/en/coins/robo-token-2',chain:'Ethereum',contract:'0x32b4d049fe4c888d2b92eecaf729f44df6b1f36e'},
PEAQ:{symbol:'PEAQ',name:'peaq',color:'#ec5198',icon:'peaq-2',fit:'Machine economy',reason:'peaq provides a network for the machine economy. PEAQ supports fees, staking, governance and machine activation bonds. Robotics is one use case within its broader machine ecosystem.',risk:'Machine activity need not translate into token gains. Emissions, adoption and competition matter. The documented fee-burn address is currently unset, so planned burns should not be treated as operating. Paper baskets only here.',source:'https://docs.peaq.xyz/peaqchain/learn/tokenomics',coingeckoId:'peaq-2',identitySource:'https://www.coingecko.com/en/coins/peaq-2',chain:'peaq',contract:'0x0000000000000000000000000000000000000809'},
AUKI:{symbol:'AUKI',name:'Auki',color:'#ed793c',icon:'auki-labs',fit:'Spatial perception',reason:'Auki’s posemesh supports shared spatial perception and navigation for devices and robots. Its documented token model uses AUKI for network access, operator staking and rewards.',risk:'Spatial-network adoption is early and may not generate material token demand. Incentives, deployment costs and competing navigation tools matter. Paper baskets only here.',source:'https://www.auki.com/posemesh/fundamentals',coingeckoId:'auki-labs',identitySource:'https://www.coingecko.com/en/coins/auki-labs',chain:'Base',contract:'0xf9569cfb8fd265e91aa478d86ae8c78b8af55df4'},
GEOD:{symbol:'GEOD',name:'GEODNET',color:'#4690c8',icon:'geodnet',fit:'Precision navigation',reason:'GEODNET supplies centimeter-level positioning through an RTK reference network, serving applications such as outdoor robots, drones and autonomous machines. GEOD incentivizes reference-station coverage.',risk:'This is navigation infrastructure, not a robot manufacturer. Regional coverage, customer usage, token emissions and the execution of project-reported buybacks matter. Paper baskets only here.',source:'https://www.geodnet.com/network',coingeckoId:'geodnet',identitySource:'https://www.coingecko.com/en/coins/geodnet',chain:'Polygon',contract:'0xac0f66379a6d7801d7726d5a943356a172549adb'},
AKT:{"symbol":"AKT","name":"Akash Network","color":"#e84635","image":"/coins/AKT-v2.png","icon":"akash-network","fit":"Cloud compute","reason":"AKT secures and governs Akash, a decentralized marketplace for compute including GPU workloads. Its cloud infrastructure is relevant to AI demand.","risk":"Compute-market competition, changing payment mechanics and network incentives can separate adoption from token returns.","source":"https://akash.network/token/"},
ATH:{"symbol":"ATH","name":"Aethir","color":"#61773d","image":"/coins/ATH-v2.png","icon":"aethir","fit":"GPU cloud","reason":"ATH is used within Aethir’s distributed GPU cloud for compute payments, staking and provider incentives, serving AI and cloud-gaming workloads.","risk":"Provider concentration, token emissions, utilization and enterprise demand affect this speculative compute exposure.","source":"https://docs.aethir.com/aethir-tokenomics/ath-tokens-utility-and-purpose"},
IO:{"symbol":"IO","name":"io.net","color":"#202020","image":"/coins/IO-v2.png","icon":"io-net","fit":"Distributed GPUs","reason":"IO is the ecosystem token for io.net, which aggregates GPU resources for compute workloads including AI. This is compute-network exposure.","risk":"Token emissions, provider verification, utilization and competing GPU services may weigh on returns.","source":"https://io.net/docs/guides/getting-started"},
GLM:{"symbol":"GLM","name":"Golem","color":"#214cad","image":"/coins/GLM-v2.png","icon":"golem-network-tokens","fit":"Compute marketplace","reason":"GLM pays providers for rented computing resources on Golem. The network supports general computation, including workloads relevant to AI.","risk":"General compute demand is not exclusively AI demand. Provider adoption, pricing and competition affect token utility.","source":"https://docs.golem.network/docs/golem/overview/golem-token"},
VIRTUAL:{"symbol":"VIRTUAL","name":"Virtuals Protocol","color":"#337d70","image":"/coins/VIRTUAL-v2.png","icon":"virtual-protocol","fit":"AI-agent economy","reason":"VIRTUAL supplies base liquidity for agent tokens in Virtuals’ onchain AI-agent ecosystem. It is platform exposure to agent creation and commerce.","risk":"Agent-token speculation, launch activity and uncertain useful demand can dominate token performance.","source":"https://whitepaper.virtuals.io/"},
GALA:{"symbol":"GALA","name":"Gala","color":"#222222","image":"/coins/GALA-v2.png","icon":"gala","fit":"Game ecosystem","reason":"GALA is a utility token for payments and digital assets in the Gala Games and Entertainment ecosystem, with network uses on GalaChain.","risk":"GALA is not equity or a claim on platform revenue. Game adoption, emissions and chain security remain risks.","source":"https://support.gala.com/hc/en-us/articles/22440779338267-What-is-GALA"},
SAND:{"symbol":"SAND","name":"The Sandbox","color":"#1597e5","image":"/coins/SAND-v2.png","icon":"the-sandbox","fit":"Creator-made worlds","reason":"SAND is the utility token and currency of The Sandbox, used within its creator, player and digital-asset economy.","risk":"Player retention and creator activity may not sustain token demand; virtual-land speculation can amplify volatility.","source":"https://docs.sandbox.game/en/owners/sand"},
MANA:{"symbol":"MANA","name":"Decentraland","color":"#e75470","image":"/coins/MANA-v2.png","icon":"decentraland","fit":"Virtual-world economy","reason":"MANA is used to price and buy Decentraland assets such as LAND, names and wearables. This is virtual-world exposure within the broader gaming thesis.","risk":"Virtual-world activity is not the same as game revenue. Thin asset markets, adoption and competing worlds affect demand.","source":"https://docs.decentraland.org/marketplace/marketplace"},
ENJ:{"symbol":"ENJ","name":"Enjin Coin","color":"#7455d8","image":"/coins/ENJ-v2.png","icon":"enjin-coin","fit":"Digital-asset infrastructure","reason":"Native ENJ powers transactions, staking and digital-asset creation on Enjin Blockchain, including ENJ-backed collectibles.","risk":"Native ENJ differs from the legacy Ethereum token. Network adoption, migration compatibility and NFT demand matter.","source":"https://docs.enjin.io/enjin-products/enjin-coin"},
CARDS:{symbol:'CARDS',name:'Collector Crypt',color:'#815ccb',icon:'collector-crypt',image:'/coins/CARDS.png',fit:'Physical-card gacha',reason:'Collector Crypt operates graded-card gacha and a marketplace for redeemable physical-card NFTs. Its documentation identifies CARDS as the ecosystem token and describes buybacks and burns.',risk:'Token value is not ownership of the vaulted cards or platform revenue. Unlocks, inventory, custody, liquidity and speculative demand matter. Solana trading is not supported in this app.',source:'https://docs.collectorcrypt.com/cards-token'},
FWA:{symbol:'FWA',name:'Fake World Assets',color:'#253d2b',icon:'fake-world-assets',image:'/coins/FWA-v2.png',fit:'NFT-pool gacha',reason:'FWA is the token of a shared NFT-pool protocol with random draws. Project documentation describes token rewards and recurring buybacks; this is digital-NFT exposure rather than physical trading cards.',risk:'NFT inventory, contract risk and liquidity matter. Transfers and authorized markets use special rules; this app has not integrated them. Available in paper baskets only.',source:'https://www.fwa.fun/docs/fwa'},
XMR:{symbol:'XMR',name:'Monero',color:'#f26822',image:'/coins/XMR-v2.png',icon:'monero',fit:'Private payments',reason:'Monero focuses on confidential payments with privacy by default. XMR is direct exposure to a privacy-focused monetary network.',risk:'Exchange access, liquidity and regulatory restrictions can materially affect demand and the ability to exit.',source:'https://www.getmonero.org/get-started/what-is-monero/'},
ZEC:{symbol:'ZEC',name:'Zcash',color:'#d4a341',image:'/coins/ZEC-v2.png',icon:'zcash',fit:'Shielded payments',reason:'Zcash supports shielded transactions using zero-knowledge proofs. ZEC is a direct privacy-sector candidate, with different privacy mechanics from Monero.',risk:'Shielded adoption, wallet support, exchange availability and development choices can affect demand.',source:'https://z.cash/learn/what-is-zcash/'},
SOL:{symbol:'SOL',name:'Solana',color:'#6851c8',image:'/coins/SOL-v2.png',icon:'solana',fit:'Application network',reason:'SOL powers a general-purpose network for applications, payments and onchain capital markets. It is broad network exposure, not ownership of businesses built on Solana.',risk:'Network competition, speculative activity and concentration of demand can amplify drawdowns.',source:'https://solana.com/'},
PUMP:{symbol:'PUMP',name:'Pump.fun',color:'#16352b',icon:'pump',image:'/coins/PUMP-v2.png',fit:'Token launch platform',reason:'PUMP is the native token of Pump.fun, a platform for creating and trading tokens. It offers platform exposure instead of selecting individual launches.',risk:'Launch activity is cyclical and highly speculative. PUMP does not confer a contractual right to platform revenues or distributions.',source:'https://pump.fun/pump-token'},
POLS:{symbol:'POLS',name:'Polkastarter',color:'#e55884',image:'/coins/POLS-v2.png',icon:'polkastarter',fit:'Launch access',reason:'POLS has utility in Polkastarter’s launch ecosystem, including staking-based eligibility for token sale participation.',risk:'Access requirements, token-sale demand and platform direction can change. Holding POLS does not guarantee allocations or returns.',source:'https://docs.polkastarter.com/what-are-the-tokenomics'},
DAO:{symbol:'DAO',name:'DAO Maker',color:'#ee7157',image:'/coins/DAO-v2.png',icon:'dao-maker',fit:'Launchpad staking',reason:'DAO Maker offers project launches, including private offerings for DAO stakers. The token is exposure to this fundraising ecosystem.',risk:'Launch quality, staking terms, platform security and liquidity affect the thesis. Token ownership is not equity in the platform.',source:'https://dao-maker-1.gitbook.io/dao-maker'},
INJ:{symbol:'INJ',name:'Injective',color:'#32a5d5',image:'/coins/INJ-v2.png',icon:'injective-protocol',fit:'Financial infrastructure',reason:'Injective provides infrastructure for tokenization and financial markets. INJ is its native network asset, an indirect platform proxy rather than ownership of tokenized stocks.',risk:'Equity-linked instruments have different structures and rights. Platform adoption need not translate into proportional INJ returns.',source:'https://injective.com/solutions/tokenization'},
GHST:{symbol:'GHST',name:'Aavegotchi',color:'#945bd1',image:'/coins/GHST-v2.png',icon:'aavegotchi',fit:'Collectible economy',reason:'Aavegotchi combines digital collectibles with a token-powered marketplace. Adjacent exposure to collecting; it does not track physical gacha sales.',risk:'Niche ecosystem; speculative demand and thin liquidity can amplify losses.',source:'https://docs.aavegotchi.com/own/tokens/ghst-token'},
IMX:{symbol:'IMX',name:'Immutable',color:'#151a1c',image:'/coins/IMX-v2.png',icon:'immutable-x',fit:'Gaming infrastructure',reason:'A blockchain ecosystem built for games and digital ownership. Broader gaming exposure, rather than a direct gacha-machine business.',risk:'Token demand may not rise with game adoption; competing chains and unlocks matter.',source:'https://www.immutable.com/chain'},
RON:{symbol:'RON',name:'Ronin',color:'#3578c5',image:'/coins/RON-v2.png',icon:'ronin',fit:'Gaming network',reason:'The ecosystem token for Ronin, a network designed for onchain games and their economies.',risk:'Depends on adoption of a concentrated gaming ecosystem and network security.',source:'https://www.roninchain.com/ron'},
AXS:{symbol:'AXS',name:'Axie Infinity',color:'#33a8b6',image:'/coins/AXS-v2.png',icon:'axie-infinity',fit:'Collectible gaming',reason:'Governance exposure to Axie’s collectible creature economy. An adjacent gaming candidate, not a physical gacha proxy.',risk:'Game retention, token issuance and speculative activity drive demand.',source:'https://axieinfinity.com/'},
USDC:{symbol:'USDC',name:'USDC',color:'#2775ca',image:'/coins/USDC-v2.png',icon:'usd-coin',fit:'Dollar stablecoin',reason:'USDC is a dollar-denominated stablecoin issued by Circle. In a stablecoin thesis, it is the intended exposure while waiting for a new market entry.',risk:'Issuer, redemption and depeg risks remain; a stablecoin is not an insured bank deposit.',source:'https://www.circle.com/usdc'},
RENDER:{symbol:'RENDER',name:'Render',color:'#ea495e',image:'/coins/RENDER-v2.png',icon:'render-token',fit:'GPU compute',reason:'A decentralized GPU rendering network; compute demand is a thematic link, not a guaranteed AI revenue claim.',risk:'Network usage and token price can diverge; competitive compute pricing matters.',source:'https://rendernetwork.com/'},
TAO:{symbol:'TAO',name:'Bittensor',color:'#242424',image:'/coins/TAO-v2.png',icon:'bittensor',fit:'Decentralized AI',reason:'An incentive network for machine intelligence, giving the basket exposure to decentralized AI experiments.',risk:'Complex emissions, subnet economics and early adoption increase uncertainty.',source:'https://bittensor.com/'},
NEAR:{symbol:'NEAR',name:'NEAR',color:'#1b302a',image:'/coins/NEAR-v2.png',icon:'near',fit:'Application infrastructure',reason:'General-purpose blockchain infrastructure with an AI-focused ecosystem. Indirect exposure to AI applications.',risk:'Application activity need not translate into proportional token value.',source:'https://near.org/'},
LINK:{symbol:'LINK',name:'Chainlink',color:'#315bda',image:'/coins/LINK-v2.png',icon:'chainlink',fit:'Data & interoperability',reason:'Oracle and interoperability infrastructure used by onchain applications, including tokenization projects.',risk:'Commercial adoption does not ensure token price appreciation.',source:'https://chain.link/'},
ONDO:{symbol:'ONDO',name:'Ondo',color:'#243d72',image:'/coins/ONDO-v2.png',icon:'ondo-finance',fit:'Tokenization ecosystem',reason:'Governance exposure to a tokenization ecosystem. Ondo offers tokenized securities, but holding ONDO is not ownership of those stocks, Treasuries, or their income.',risk:'Governance rights differ from cash-flow rights; regulatory and unlock risks matter.',source:'https://ondo.finance/'},
ETH:{symbol:'ETH',name:'Ethereum',color:'#7182b6',image:'/coins/ETH-v2.png',icon:'ethereum',fit:'Settlement layer',reason:'Settlement and application infrastructure for onchain assets and financial applications.',risk:'Market volatility, scaling competition and smart-contract ecosystem risks.',source:'https://ethereum.org/'},
BTC:{symbol:'BTC',name:'Bitcoin',color:'#f7931a',image:'/coins/BTC-v2.png',icon:'bitcoin',fit:'Digital scarcity',reason:'A scarce digital asset for a monetary adoption thesis, independent of gaming or AI activity.',risk:'Volatile demand and no contractual income or price floor.',source:'https://bitcoin.org/'}
};
const base={createdAt:1789990000000,version:1,engine:'curated' as const,example:true,author:'Shot Call editorial'};
export const EXAMPLES:Thesis[]=[
{...base,id:VITALIK_CALL_ID,title:'In Vitalik We Trust',body:'My call: Vitalik can do no wrong. The builder who helped create Ethereum has an eye for what comes next. I’m buying the tokens of projects he publicly invested in: Starknet through StarkWare, MegaETH and Aztec. Back his bets across scaling, real-time execution and programmable privacy.',summary:'Back the builder. Buy his bets.',category:'Ethereum',createdAt:Date.parse('2026-09-30T11:30:00Z'),allocations:[{symbol:'STRK',weight:34},{symbol:'MEGA',weight:33},{symbol:'AZTEC',weight:33}],evidenceNote:'Public investment links and token identities reviewed September 30, 2026. This is a roughly equal-weight token basket, not Vitalik’s personal portfolio. Private investments and project tokens carry different rights. Other documented projects appear below; this is not an exhaustive list of private holdings.',risk:'Conviction in a founder is not a guarantee of returns. These tokens are correlated Ethereum ecosystem exposure, with adoption, liquidity, emissions and execution risks. Historical investment does not establish current token ownership or endorsement. Nocturne’s wind-down is a concrete counterexample to the premise.'},
{...base,id:'game-over',title:'Game Over',body:'I’m bearish on the gaming-token sector. I expect token incentives and speculative valuations to outrun lasting player demand. Short a broad basket of gaming networks, game economies and virtual-world tokens rather than betting against just one project.',summary:'Ten gaming tokens. One sector-wide short.',category:'Gaming',createdAt:1790763000000,allocations:['IMX','RON','AXS','GALA','SAND','MANA','ENJ','GHST','BEAM','ILV'].map(symbol=>({symbol,weight:10,side:'short' as const})),evidenceNote:'A broad ten-token gaming short basket, the maximum size of a take. Every allocation is a 1× simulated short, with 10% of capital assigned to each. This covers selected gaming projects rather than every gaming token in existence. Project sources identify the exposures; they are not evidence that prices will fall. No live shorts or exchange orders are placed.',risk:'Gaming tokens can rally together, and individual game launches or short squeezes can defeat the thesis. In this 1× simulation, a 10% fall across the underlyings gains about 10% before fees; a 10% rise loses about 10%. Losses are capped at this position’s value. Borrowing costs, funding, liquidity and real short-liquidation mechanics are excluded.'},
{...base,id:'pokemon-repacks',title:'Pokémon, Repacked',body:'Pokémon cards and repack products are going onchain. Graded physical-card packs and digital NFT pools are becoming a consumer crypto category.',summary:'Physical-card grails. Digital repacks. A new collecting economy.',category:'Cards & repacks',createdAt:1790727600002,allocations:[{"symbol":"CARDS","weight":82},{"symbol":"FWA","weight":18}],evidenceNote:'Project sources and token identities reviewed September 29, 2026. CARDS is physical-card platform exposure; FWA is a separate digital NFT repack exposure, not Pokémon cards. Products without a verified platform token are linked below. Illustrative paper weights, not an exhaustive or live AI scan.',risk:'Concentrated and speculative. Card demand, custody, token unlocks and liquidity matter. Platform tokens do not own the cards or guarantee revenue rights. Growth in collecting need not produce token gains; competing platforms may capture activity. Both thematic tokens are paper-only here.'},
{...base,id:'robotics-economy',title:'Robots Need Rails',body:'Robots will need identity, payments, spatial intelligence and precise navigation. The crypto rails behind physical autonomy will matter.',summary:'The payment, perception, and navigation rails behind autonomous machines.',category:'Robotics',createdAt:1790727600001,allocations:[{"symbol":"ROBO","weight":33},{"symbol":"PEAQ","weight":28},{"symbol":"AUKI","weight":22},{"symbol":"GEOD","weight":17}],evidenceNote:'Project sources and exact CoinGecko identities reviewed September 29, 2026. ROBO targets robot coordination; PEAQ covers the broader machine economy; AUKI supplies spatial perception; GEOD supports precise outdoor navigation. Illustrative paper weights, not equity in robot manufacturers or a live AI scan.',risk:'Early infrastructure and a correlated narrative. Real robot adoption may not create token demand. Unlocks, emissions, coverage, implementation and thin liquidity can dominate returns. The thematic holdings are paper-only in this app.'},
{...base,"id":"intelligence-economy-expanded","parent":"intelligence-economy","title":"The Intelligence Economy","body":"AI will need more compute, open intelligence networks, and an economy of its own.","summary":"Compute, intelligence, and agents. Nine exposures, one conviction.","category":"AI & compute","createdAt":1790715600002,"allocations":[{"symbol":"RENDER","weight":20},{"symbol":"TAO","weight":20},{"symbol":"AKT","weight":13},{"symbol":"ATH","weight":11},{"symbol":"IO","weight":9},{"symbol":"GLM","weight":8},{"symbol":"VIRTUAL","weight":9},{"symbol":"NEAR","weight":7},{"symbol":"LINK","weight":3}],"evidenceNote":"A nine-token curated example, fully allocated to thematic holdings. Includes compute networks, machine intelligence, AI-agent platforms and smaller infrastructure positions. Project sources reviewed September 29, 2026; weights are illustrative.","risk":"Correlated AI narratives can fall together. Compute usage and agent activity need not translate into token returns; emissions, concentration and competition matter.","version":2},
{...base,"id":"onchain-gaming-expanded","parent":"onchain-gaming","title":"Play, Collect, Own","body":"Onchain games and their collectible economies will grow.","summary":"Games, creator worlds, and the infrastructure behind ownership.","category":"Gaming","createdAt":1790715600001,"allocations":[{"symbol":"IMX","weight":20},{"symbol":"RON","weight":17},{"symbol":"GHST","weight":13},{"symbol":"AXS","weight":11},{"symbol":"GALA","weight":11},{"symbol":"SAND","weight":9},{"symbol":"MANA","weight":7},{"symbol":"ENJ","weight":7},{"symbol":"ATH","weight":5}],"evidenceNote":"A nine-token curated example, fully allocated to gaming, virtual-world and infrastructure holdings. Project sources reviewed September 29, 2026. Each role is distinguished below; weights are illustrative.","risk":"Game economies, virtual worlds and infrastructure have different drivers. Player retention, token emissions and concentrated ecosystem demand can overwhelm adoption growth. These are broad gaming exposures, not physical-gacha tokens.","version":2},
{...base,createdAt:1790707000006,id:'gacha-collectibles',title:'The Gacha Supercycle',body:'I’m big on gacha. Physical-card pulls and onchain collectible machines are becoming a new consumer crypto category.',summary:'The tokens behind the pull. The products behind the conviction.',category:'Gacha & collectibles',version:2,parent:'gacha-supercycle',allocations:[{"symbol":"CARDS","weight":67},{"symbol":"FWA","weight":33}],evidenceNote:'Research reviewed September 29, 2026. CARDS targets physical-card gacha; FWA targets digital NFT pools. These are the two direct candidates with token identities checked in the current directory. Other candidates appear below. This is a curated paper basket, not an exhaustive or live AI scan.',risk:'A concentrated, speculative basket. Weights are illustrative. CARDS and FWA have different products and token mechanics; neither is equity or guaranteed exposure to gacha revenue. Both are paper-only in this app.'},
{...base,id:'onchain-gaming',title:'Play, Collect, Own',body:'Onchain games and their collectible economies will grow.',summary:'The games, worlds, and networks behind digital ownership.',category:'Gaming',allocations:[{"symbol":"GHST","weight":39},{"symbol":"IMX","weight":28},{"symbol":"RON","weight":22},{"symbol":"AXS","weight":11}],risk:'Collectible-game tokens and gaming infrastructure have different demand drivers. This is broad gaming exposure, not a basket of gacha platforms.'},
{...base,createdAt:1790707000005,id:'privacy-repriced',title:'Privacy, Repriced',body:'Privacy coins are going to rip.',summary:'A new bid for financial privacy.',category:'Privacy',allocations:[{"symbol":"XMR","weight":56},{"symbol":"ZEC","weight":44}],risk:'A concentrated sector thesis. Privacy adoption does not guarantee price appreciation; exchange access and liquidity may deteriorate.'},
{...base,createdAt:1790707000004,id:'majors-bottom',title:'The Majors Bottom',body:'This is the bottom for the majors.',summary:'Back the core assets before the next leg up.',category:'Majors',allocations:[{"symbol":"BTC","weight":44},{"symbol":"ETH","weight":39},{"symbol":"SOL","weight":17}],risk:'A bottom is a hypothesis, not a verified signal. Major assets remain correlated and may suffer further large drawdowns.'},
{...base,createdAt:1790707000003,id:'eth-to-7000',title:'ETH to $7,000',body:'ETH is positioned to run to $7,000 based on the new paper Vitalik released.',summary:'One asset. One catalyst. A high-conviction view.',category:'Ethereum',allocations:[{"symbol":"ETH","weight":100}],evidenceNote:'Paper source needed. No title or link was supplied, so the paper has not been identified or assessed. $7,000 is the author’s target, not a verified forecast.',risk:'This is a concentrated ETH thesis. A technical paper alone does not establish a price target, timing or probability. No price-target exit is armed; demo exits use percentage moves.'},
{...base,createdAt:1790707000002,id:'launchpad-economy',title:'The Launchpad Economy',body:'Launchpads are the only thing worth investing in.',summary:'Back the platforms where new tokens begin.',category:'Launchpads',allocations:[{"symbol":"PUMP","weight":44},{"symbol":"POLS","weight":28},{"symbol":"DAO","weight":28}],risk:'Illustrative platform-token exposure, not an endorsement of every token launched. Launch demand is cyclical and platform tokens are not shares in their businesses.'},
{...base,createdAt:1790707000001,id:'stock-tokens-win',title:'Wall Street, Onchain',body:'Stock token platforms are going to win.',summary:'The platforms and rails behind tokenized equities.',category:'Stock tokens',allocations:[{"symbol":"ONDO","weight":44},{"symbol":"INJ","weight":28},{"symbol":"LINK","weight":17},{"symbol":"SOL","weight":11}],risk:'These are governance and infrastructure proxies. They are not tokenized stocks, shares of the platforms, or claims on equity-market revenues. Legal rights and availability differ by product.'},
{...base,id:'gacha-supercycle',title:'The Gacha Supercycle',body:'I’m big on gacha. The next generation of collectors will trade, play, and own their collectibles onchain.',summary:'The next generation of collectors is onchain.',category:'Gaming',allocations:[{"symbol":"GHST","weight":39},{"symbol":"IMX","weight":28},{"symbol":"RON","weight":22},{"symbol":"AXS","weight":11}],risk:'These are adjacent gaming and collectible tokens. None is a verified direct investment in physical gacha-machine sales.'},
{...base,id:'intelligence-economy',title:'The Intelligence Economy',body:'AI will need more compute, open intelligence networks, and an economy of its own.',summary:'The picks and shovels behind machine intelligence.',category:'AI & compute',allocations:[{"symbol":"RENDER","weight":34},{"symbol":"TAO","weight":33},{"symbol":"NEAR","weight":22},{"symbol":"LINK","weight":11}],risk:'AI narratives are speculative. Growing demand for AI does not guarantee that these tokens capture its value.'},
{...base,id:'everything-onchain',title:'Everything, Onchain',body:'Real-world assets will move onchain. The infrastructure behind tokenization will matter as much as the assets.',summary:'A new home for the world’s assets.',category:'Real-world assets',allocations:[{"symbol":"ONDO","weight":34},{"symbol":"LINK","weight":33},{"symbol":"ETH","weight":33}],risk:'Governance and infrastructure tokens are not claims on the underlying real-world assets or their yield.'},
{...base,id:'digital-hard-money',title:'A New Kind of Hard Money',body:'Digital scarcity and open settlement will become a bigger part of the global financial system.',summary:'Scarcity, without borders.',category:'Macro',allocations:[{"symbol":"BTC","weight":61},{"symbol":"ETH","weight":39}],risk:'Monetary adoption is uncertain. Both assets can suffer significant and sustained drawdowns.'},
{...base,id:'bitcoin-amplified',title:'Bitcoin, Amplified',body:'Bitcoin is ready for its next leg up. I want to express that conviction with a leveraged long BTC perpetual.',summary:'One asset. More exposure. A clearly defined liquidation level.',category:'Majors',createdAt:1790745000000,executionVersion:1,allocations:[{symbol:'BTC',weight:100,execution:'perps',leverage:3}],exitPlan:{id:'bitcoin-creator-exits-v1',mode:'basket',steps:[{symbol:null,targetPct:30,sellPct:50},{symbol:null,targetPct:60,sellPct:50}],stopLossPct:20,rationale:'Take half the profit at a 30% return on collateral and the rest at 60%. Exit the basket if the loss reaches 20%.',origin:'creator',updatedAt:1790745000000},evidenceNote:'A creator-configured perpetual example. Execution and exit settings are shown below; review the estimated liquidation price before confirming. Market availability and mark prices are checked against Hyperliquid; the position and collateral are simulated.',risk:'Leveraged longs amplify losses as well as gains. Liquidation can consume your allocated collateral. Prices shown before confirmation are estimates under this app’s simplified demo model; funding, slippage, margin tiers and external venue costs are excluded.'},
{...base,id:'week-in-stables',title:'A Week on the Sidelines',body:'Be in stables for this next week. I want to hold dollar stablecoins while I wait for a better entry into crypto.',summary:'Sit out the volatility. Keep the next move open.',category:'Stables',createdAt:1790729500001,allocations:[{symbol:'USDC',weight:100}],evidenceNote:'An explicit one-week stablecoin thesis. USDC is the exposure itself. This demo does not provide yield or automatically exit after seven days. Review the issuer and reserve sources below.',risk:'USDC carries issuer, redemption, custody, network and depeg risks. It is not an insured bank deposit. Markets can rise while this take waits. The 0.05% entry fee applies even to stablecoin takes; realized gains carry the published performance fee.'},
{...base,id:'hormuz-reopened',title:'Hormuz, Reopened',body:'The Strait of Hormuz is going to reopen and normal shipping will return by November 30. I expect the disruption premium in oil to unwind: short oil-linked stock tokens and back YES on Polymarket.',summary:'Short the oil premium. Back the return of normal shipping.',category:'Geopolitics & oil',createdAt:1790729400001,allocations:[{"symbol":"BNOON","weight":45,"side":"short"},{"symbol":"USOON","weight":33,"side":"short"},{"symbol":"HORMUZYES","weight":22}],evidenceNote:'Illustrative paper strategy: 45% Brent-fund short collateral, 33% WTI-fund short collateral and 22% Polymarket YES allocation. The external market was open when reviewed September 29, 2026; check its current status and price. Stock tokens are not inverse funds. No live shorts, Polymarket orders or automatic event settlement are connected.',risk:'Reopening may not lower oil prices. Inventory shortages, futures roll, tracking, borrowing costs, squeezes and renewed disruption can change returns. YES requires the specific traffic threshold by November 30 and may expire worthless. Paper shorts are limited to the simulated portfolio value and omit real borrowing mechanics.'}
];
// Editorial examples demonstrate creator-set schedules; these are illustrative,
// not AI-generated recommendations or live market orders.
for(const take of EXAMPLES){
 if(take.id==='majors-bottom')take.exitPlan={id:'editorial-majors-v1',mode:'basket',steps:[{symbol:null,targetPct:20,sellPct:25},{symbol:null,targetPct:40,sellPct:25},{symbol:null,targetPct:70,sellPct:50}],rationale:'Take some profit as the rebound develops, then hold the remaining half for a stronger recovery. These percentage targets are illustrative, not a forecast of the bottom.',origin:'creator',updatedAt:take.createdAt};
 if(take.id==='gacha-collectibles')take.exitPlan={id:'editorial-gacha-v1',mode:'tokens',steps:take.allocations.filter(a=>a.weight>0).flatMap((a,i)=>[{symbol:a.symbol,targetPct:20+i*5,sellPct:50},{symbol:a.symbol,targetPct:50+i*5,sellPct:50}]),rationale:'Scale out of each project independently as the collectibles thesis develops. Real product adoption and token utility matter; a successful product does not guarantee its token will appreciate.',origin:'creator',updatedAt:take.createdAt};
}
export const EXAMPLE_UPDATES:Record<string,string>={'gacha-supercycle':'gacha-collectibles','intelligence-economy':'intelligence-economy-expanded','onchain-gaming':'onchain-gaming-expanded'};
export const DEMO_SUGGESTIONS=[
  {label:'Gacha supercycle',take:'Gacha is the next big thing'},
  {label:'Privacy coins rip',take:'Privacy coins are going to rip'},
  {label:'The majors bottom',take:'This is the bottom for the majors'},
  {label:'ETH to $7,000',take:'ETH is positioned to run to 7,000 based on the new paper Vitalik released'},
  {label:'Launchpads win',take:'Launchpads are the only thing worth investing in'},
  {label:'Stocks go onchain',take:'Stock tokens platforms are going to win'}
];
// Specific theses precede broader narratives: a stock-token platform is not
// the same basket as generic tokenization, and ETH conviction is not generic AI.
const thesisMatchers:[RegExp,string][]=[
  [VITALIK_PORTFOLIO_PROMPT,VITALIK_CALL_ID],
  [/\b(?:short(?:ing)?|bearish|bet against)\b[\s\S]*\b(?:gaming|gamefi|game tokens?)\b|\b(?:gaming|gamefi|game tokens?)\b[\s\S]*\b(?:short(?:ing)?|bearish)\b/i,'game-over'],
  [/\bhormuz\b|\bshort(?:ing)?\s+(?:crude\s+)?oil\b/i,'hormuz-reopened'],
  [/\bpok[eé]mon\b|\btrading[ -]cards?\b|\brepacks?\b|\brepackaging\b/i,'pokemon-repacks'],
  [/\brobotics\b|\brobots?\b|\bautonomous[ -]machines?\b|\bfabric protocol\b|\bpeaq\b|\bauki\b|\bgeodnet\b/i,'robotics-economy'],
  [/\bg(?:a|o)t?chas?\b|\bgachapons?\b|collector crypt|powergacha|fake world assets|\bfwa\b|courtyard|phygitals|beezie|gacha fund|bye\.fun|\bcardx\b|\bblind[ -]?box|\bcard (?:pull|pack)|\bcollectibles?\b|\bpok[eé]mon\b/i,'gacha-collectibles'],
  [/\bprivacy\b|\bmonero\b|\bzcash\b|\bprivacy coins?\b/i,'privacy-repriced'],
  [/\blaunch\s?pads?\b|\bpump\.fun\b|\bpolkastarter\b|\bdao maker\b/i,'launchpad-economy'],
  [/\bstock\b|\bstocks\b|\bequit(?:y|ies)\b|\bxstocks\b/i,'stock-tokens-win'],
  [/\bmajors?\b|\bblue[ -]?chips?\b/i,'majors-bottom'],
  [/\beth\b|\bethereum\b|\bvitalik\b/i,'eth-to-7000'],
  [/\bgaming\b|\bgames?\b|\baxie\b|\baavegotchi\b/i,'onchain-gaming'],
  [/\bai\b|\bintelligence\b|\bcompute\b|\bgpus?\b/i,'intelligence-economy'],
  [/tokeniz|tokenis|real.world|treasur|\brwa\b/i,'everything-onchain'],
  [/bitcoin|scarcity|inflation|hard money/i,'digital-hard-money']
];
export function curatedTake(take:string):Thesis|null {
  const id=wantsStablecoins(take)?'week-in-stables':thesisMatchers.find(([pattern])=>pattern.test(take))?.[1];
  const source=EXAMPLES.find(t=>t.id===(id?EXAMPLE_UPDATES[id]||id:undefined));
  if(!source)return null;
  const result={...source,id:crypto.randomUUID(),body:take,example:false,parent:source.id,version:1,createdAt:Date.now()};
  if(source.id==='eth-to-7000'){
    // Never introduce the seed example's catalyst or $7,000 target into a
    // different ETH take. The user's actual wording controls those claims.
    const hasTarget=/7[, ]?000|7k\b/i.test(take);
    const mentionsPaper=/paper|vitalik|research/i.test(take);
    result.title=hasTarget?'ETH to $7,000':'The Ethereum Thesis';
    result.summary=mentionsPaper?'An ETH thesis with a catalyst to verify.':'A focused expression of Ethereum conviction.';
    result.evidenceNote=mentionsPaper?'Paper source needed. This demo has not identified or assessed the referenced research. Any price target is the author’s view, not a verified forecast.':undefined;
  }
  return result;
}
export const dollars=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
