import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const accounts=sqliteTable('accounts',{userId:text('user_id').primaryKey(),balance:integer('balance').notNull().default(1000000),revision:integer('revision').notNull().default(0),demoWalletConnected:integer('demo_wallet_connected').notNull().default(0),defaultBuyAmount:integer('default_buy_amount').notNull().default(10000)});
export const theses=sqliteTable('theses',{id:text('id').primaryKey(),owner:text('owner').notNull(),payload:text('payload').notNull(),visibility:text('visibility').notNull().default('public'),artworkId:text('artwork_id'),closedAt:integer('closed_at'),archivedAt:integer('archived_at'),createdAt:integer('created_at').notNull()},t=>[index('theses_owner_idx').on(t.owner),index('theses_created_idx').on(t.createdAt)]);
export const positions=sqliteTable('positions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),thesisId:text('thesis_id').notNull(),amount:integer('amount').notNull(),invested:integer('invested').notNull(),takeProfit:integer('take_profit'),stopLoss:integer('stop_loss'),shareEligible:integer('share_eligible').notNull().default(0),shareCreator:text('share_creator'),shareRealized:integer('share_realized').notNull().default(0),shareHighWater:integer('share_high_water').notNull().default(0),sharePaid:integer('share_paid').notNull().default(0),platformRealized:integer('platform_realized').notNull().default(0),platformHighWater:integer('platform_high_water').notNull().default(0),platformPaid:integer('platform_paid').notNull().default(0),executionMode:text('execution_mode').notNull().default('spot'),leverage:integer('leverage').notNull().default(1),perpNotional:integer('perp_notional').notNull().default(0),perpWeight:integer('perp_weight').notNull().default(0),maintenanceBps:integer('maintenance_bps').notNull().default(0),perpMarkets:text('perp_markets'),feeTerms:text('fee_terms'),executionState:text('execution_state'),exitState:text('exit_state')},t=>[uniqueIndex('positions_user_thesis').on(t.userId,t.thesisId)]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),userId:text('user_id').notNull(),thesisId:text('thesis_id').notNull(),side:text('side').notNull(),amount:integer('amount').notNull(),creatorFee:integer('creator_fee').notNull().default(0),tradingFee:integer('trading_fee').notNull().default(0),platformProfitFee:integer('platform_profit_fee').notNull().default(0),feeTerms:text('fee_terms'),feePolicy:text('fee_policy').notNull().default('legacy'),executionMode:text('execution_mode').notNull().default('spot'),leverage:integer('leverage').notNull().default(1),executionReason:text('execution_reason'),costBasis:integer('cost_basis'),requestKey:text('request_key'),operationId:text('operation_id'),createdAt:integer('created_at').notNull()},t=>[index('orders_user_idx').on(t.userId,t.createdAt)]);
export const generations=sqliteTable('generations',{id:text('id').primaryKey(),owner:text('owner').notNull(),prompt:text('prompt').notNull(),model:text('model').notNull(),status:text('status').notNull(),result:text('result'),providerPayload:text('provider_payload'),usage:text('usage'),estimatedCostCents:integer('estimated_cost_cents'),error:text('error'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('generations_owner_created_idx').on(t.owner,t.createdAt)]);

export const creatorProfiles=sqliteTable('creator_profiles',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),twitterHandle:text('twitter_handle').notNull(),bio:text('bio').notNull().default(''),avatarKey:text('avatar_key'),bannerKey:text('banner_key'),publicInvestments:integer('public_investments'),leaderboardOptIn:integer('leaderboard_opt_in').notNull().default(0),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('creator_profiles_user_idx').on(t.userId)]);

export const thesisFollows=sqliteTable('thesis_follows',{userId:text('user_id').notNull(),thesisId:text('thesis_id').notNull(),creatorId:text('creator_id').notNull(),active:integer('active').notNull().default(1),acceptedAt:integer('accepted_at').notNull()},t=>[uniqueIndex('follows_user_thesis_idx').on(t.userId,t.thesisId),index('follows_creator_idx').on(t.creatorId,t.active)]);
export const creatorEarnings=sqliteTable('creator_earnings',{orderId:text('order_id').primaryKey(),creatorId:text('creator_id').notNull(),followerId:text('follower_id').notNull(),thesisId:text('thesis_id').notNull(),amount:integer('amount').notNull(),realizedProfit:integer('realized_profit').notNull(),createdAt:integer('created_at').notNull()},t=>[index('earnings_creator_idx').on(t.creatorId,t.createdAt)]);

export const evidenceReports=sqliteTable('evidence_reports',{id:text('id').primaryKey(),owner:text('owner').notNull(),thesisId:text('thesis_id').notNull(),fingerprint:text('fingerprint').notNull(),prompt:text('prompt').notNull(),model:text('model').notNull(),status:text('status').notNull(),result:text('result'),providerPayload:text('provider_payload'),usage:text('usage'),estimatedCostCents:integer('estimated_cost_cents'),error:text('error'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('evidence_thesis_idx').on(t.thesisId,t.fingerprint,t.createdAt),index('evidence_owner_idx').on(t.owner,t.createdAt)]);

export const peopleFollows=sqliteTable('people_follows',{followerId:text('follower_id').notNull(),followeeId:text('followee_id').notNull(),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('people_follows_pair_idx').on(t.followerId,t.followeeId),index('people_follows_followee_idx').on(t.followeeId)]);

export const predictionRounds=sqliteTable('prediction_rounds',{id:text('id').primaryKey(),thesisId:text('thesis_id').notNull(),days:integer('days').notNull(),sequence:integer('sequence').notNull(),thesisVersion:integer('thesis_version').notNull(),title:text('title').notNull(),basket:text('basket').notNull(),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),status:text('status').notNull().default('open'),outcome:text('outcome'),returnPct:integer('return_micropct'),reason:text('reason'),prices:text('prices'),settlementId:text('settlement_id'),settledAt:integer('settled_at')},t=>[uniqueIndex('prediction_round_sequence').on(t.thesisId,t.days,t.sequence),index('prediction_round_due').on(t.status,t.endsAt)]);
export const predictionBets=sqliteTable('prediction_bets',{id:text('id').primaryKey(),roundId:text('round_id').notNull(),userId:text('user_id').notNull(),side:text('side').notNull(),amount:integer('amount').notNull(),stake:integer('stake').notNull(),fee:integer('fee').notNull(),payout:integer('payout'),requestKey:text('request_key').notNull(),operationId:text('operation_id').notNull(),createdAt:integer('created_at').notNull()},t=>[index('prediction_bets_round').on(t.roundId),index('prediction_bets_user').on(t.userId)]);

export const takeIdentities=sqliteTable('take_identities',{id:text('id').primaryKey(),owner:text('owner').notNull(),thesisId:text('thesis_id').notNull(),body:text('body').notNull(),category:text('category').notNull(),title:text('title').notNull(),prompt:text('prompt'),status:text('status').notNull(),imageKey:text('image_key'),error:text('error'),requestHash:text('request_hash').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('take_identity_owner_idx').on(t.owner,t.createdAt)]);

export const pnlCards=sqliteTable('pnl_cards',{id:text('id').primaryKey(),userId:text('user_id').notNull(),payload:text('payload').notNull(),imageKey:text('image_key').notNull(),createdAt:integer('created_at').notNull()});

export const appMembers=sqliteTable('app_members',{userId:text('user_id').primaryKey(),invitedBy:text('invited_by'),source:text('source').notNull(),joinedAt:integer('joined_at').notNull()});
export const memberInvites=sqliteTable('member_invites',{code:text('code').primaryKey(),inviterId:text('inviter_id').notNull(),slot:integer('slot').notNull(),claimedBy:text('claimed_by'),claimedAt:integer('claimed_at'),createdAt:integer('created_at').notNull()},t=>[uniqueIndex('member_invites_inviter_slot').on(t.inviterId,t.slot),uniqueIndex('member_invites_claimed_by').on(t.claimedBy)]);
export const membershipSettings=sqliteTable('membership_settings',{key:text('key').primaryKey(),value:text('value').notNull()});

export const exitSuggestions=sqliteTable('exit_suggestions',{id:text('id').primaryKey(),owner:text('owner').notNull(),requestHash:text('request_hash').notNull(),status:text('status').notNull(),result:text('result'),error:text('error'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('exit_suggestions_owner_created_idx').on(t.owner,t.createdAt)]);
